service: goserverless

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "autoscaling:Describe*"
        - "cloudwatch:Describe*"
        - "cloudwatch:Get*"
        - "cloudwatch:List*"
        - "logs:Get*"
        - "logs:List*"
        - "logs:Describe*"
        - "logs:TestMetricFilter"
        - "logs:FilterLogEvents"
        - "sns:Get*"
        - "sns:List*"
      Resource:
        - "*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  billing_notify:
    handler: bin/main
    events:
      - schedule: cron(0 23 * * ? *)
    environment:
      LINEpostURL: https://notify-api.line.me/api/notify
      LINEnotyfyToken: <Token>
